# Site settings
title: Thoughts Out
email: cfabianski@me.com
github: "https://github.com/cfabianski"
description: "Technical blog to improve your Rails application."
baseurl: ""
url: "http://cfabianski.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Keybase
include: [".well-known"]

# Gems
gems:
  - jemoji
